FROM node:22-alpine

WORKDIR /app
ENV CI=true
COPY apps/web/package.json apps/web/pnpm-lock.yaml apps/web/pnpm-workspace.yaml ./
RUN corepack enable && pnpm install --frozen-lockfile
COPY apps/web ./
CMD ["pnpm", "dev", "--host", "0.0.0.0"]
